# Workflow name
name: 'Publish'

# Event for the workflow
on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'fix/**'

# List of jobs
jobs:
  publish-package:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          #registry-url: https://npm.pkg.github.com/
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install dependencies
        run: pnpm install

      - name: Unit tests
        run: pnpm run test

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Build
        run: pnpm run build

      - name: Publish
        working-directory: ./dist
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
